# -*- coding: utf-8 -*-
"""
/***************************************************************************
 StreetFacingSide
                                 A QGIS plugin
 Identifies the side of the polygon (e.g. parcels or building footprints) that is facing the street, river, or any other line vector file type. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-06
        copyright            : (C) 2023 by Blair William Gerald Scriven
        email                : scrivenblair@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load StreetFacingSide class from file StreetFacingSide.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Street_Facing_Side import StreetFacingSide
    return StreetFacingSide(iface)
